export enum MenuKey {
  //
  HOMEPAGE = 'HOMEPAGE',
  //
  PRODUCT = 'PRODUCT',
  PRODUCT_LIST = 'PRODUCT_LIST',
  PRODUCT_ADD = 'PRODUCT_ADD',
  PRODUCT_SETTING = 'PRODUCT_SETTING',
  //
  PORTFOLIO = 'PORTFOLIO',
  PORTFOLIO_LIST = 'PORTFOLIO_LIST',
  PORTFOLIO_ADD = 'PORTFOLIO_ADD',
  //
  BLOG = 'BLOG',
  BLOG_LIST = 'BLOG_LIST',
  BLOG_ADD = 'BLOG_ADD',
  BLOG_CATEGORY = 'BLOG_CATEGORY',
  //
  ORDER_TRACKING = 'ORDER_TRACKING',
}
